### ISSUE TITLE
Consider adding Go Module compatible tags

### ISSUE THREAD

**Issue by SamWhited** [tmsmr/xmpp-webhook#14]
Go module uses tags in semver form and prefixed by a "v". Please consider adding tags in a format that is compatible with Go modules so that existing Go tooling can be used to easily download this module. Thanks.

```
git tag v0.1.0 0.1
git tag v0.2.0 0.2
git tag v0.3.0 0.3
```

**Comment by tmsmr** [comment]
Thanks for the hint. I updated the tags accordingly!
